# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0732840747a61aba78c9151102248782"
name = "popular-products-orders"
handle = "popular-products-orders"
application_url = "https://keys-nokia-excitement-brick.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nicks-jewelry-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders"

[auth]
redirect_urls = [
  "https://keys-nokia-excitement-brick.trycloudflare.com/auth/callback",
  "https://keys-nokia-excitement-brick.trycloudflare.com/auth/shopify/callback",
  "https://keys-nokia-excitement-brick.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
